
name: ermes_storage
description: Sistema di storage e caching per Ermes con supporto a politiche FIFO/LIFO.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  work_db: ^1.2.0
  barrel_files_annotation: ^0.3.0
  singleton_manager: ^0.4.2
  iermes:
    path: ../iermes

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.7.1
  index_generator: ^4.1.0
  singleton_manager_generator: ^1.1.2

scripts:
  barrels:
    run: dart run build_runner build --delete-conflicting-outputs

  analyze:
    run: dart analyze
