
name: ermes_core
description: Implementation of Ermes interfaces for peer-to-peer messaging
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  meta: ^1.11.0
  barrel_files_annotation: ^0.3.0
  iermes:
    path: ../iermes
  ermes_storage:
    path: ../ermes_storage
  ermes_signaling:
    path: ../ermes_signaling
  ermes_cipher:
    path: ../ermes_cipher
  ermes_id_handler:
    path: ../ermes_id_handler
  ermes_message_control:
    path: ../ermes_message_control
  uuid: ^4.5.1
  stun_shsp: ^0.2.2
  callback_handler: ^0.0.3
  crypto: ^3.0.3
  cryptdart: ^0.2.0
  json_annotation: ^4.10.0
  singleton_manager: ^0.6.1


  ermes_core_init: any
dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.7.1
  index_generator: ^4.1.0
  json_serializable: ^6.8.0
  singleton_manager_generator: ^1.4.0
  test: ^1.24.0

scripts:
  barrels:
    run: dart run build_runner build --delete-conflicting-outputs

  analyze:
    run: dart analyze
