name: ermes_signaling
description: Signaling layer implementation for Ermes peer-to-peer messaging
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  meta: ^1.11.0
  barrel_files_annotation: ^0.3.0
  iermes:
    path: ../iermes
  signaling_contract_sdk: 2.0.0
  web3dart: ^3.0.1
  cryptdart: ^0.2.0  # Aggiornata alla versione più recente
  shsp_interfaces: ^1.1.0
  stun: ^1.0.1
  shsp_implementations: ^1.0.6
  shsp_types: ^1.1.0
  wallet: ^0.0.18

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  http: ^1.1.0
  build_runner: ^2.7.1
  index_generator: ^4.1.0

scripts:
  barrels:
    run: dart run build_runner build --delete-conflicting-outputs

  analyze:
    run: dart analyze

