name: ermes_signaling
description: Signaling layer implementation for Ermes peer-to-peer messaging
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  meta: ^1.11.0
  ermes_types:
    path: ../types
  iermes:
    path: ../iermes
  signaling_contract_sdk: 1.0.2
  web3dart: ^3.0.1
  cryptdart: ^0.1.2  # Aggiornata alla versione più recente
  barrel_files_annotation: ^0.2.0
  shsp_interfaces: ^1.0.0
  shsp_implementations: ^1.0.2
  stun: ^1.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  http: ^1.1.0

