classDiagram
  class ErmesCachingRepository_D_ {
    <<class>>
    📁 ermes_caching_repository.dart
  }
  class ErmesCachingService_DataJson_ {
    <<class>>
    📁 ermes_caching_service.dart
  }
  class _ErmesCachingServiceOptions {
    <<class>>
    📁 ermes_storage_and_caching.dart
  }
  class CachingMode {
    <<enumeration>>
    📁 ermes_storage_and_caching.dart
  }
  class ErmesStorageAndCaching_DataJson_ {
    <<class>>
    📁 ermes_storage_and_caching.dart
  }
  class ErmesStorageAndCachingMessages_DataJson_ {
    <<class>>
    📁 ermes_storage_and_caching_messages.dart
  }
  class ErmesStorageAndCachingMessagesHandler {
    <<class>>
    📁 ermes_storage_and_caching_messages_handler.dart
  }
  class ErmesStorageRepository_DataJson_ {
    <<class>>
    📁 ermes_storage_repository.dart
  }
  class ErmesStorageService_DataJson_ {
    <<class>>
    📁 ermes_storage_service.dart
  }
  class TestCacheMessage {
    <<class>>
    📁 caching_repository_test.dart
  }
  class TestCachingServiceMessage {
    <<class>>
    📁 caching_service_test.dart
  }
  class MockStorage_T_ {
    <<class>>
    📁 integration_test.dart
  }
  class MockStorageRepository_T_ {
    <<class>>
    📁 storage_service_test.dart
  }
  class IErmesCachingRepository {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IdType {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesCachingService {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class DataJson {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesStorageAndCaching {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesStorageRepository {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class ErmesStorageAndCaching {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesStorageAndCachingMessages {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IdConnectionType {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class ErmesStorageAndCachingMessages {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class StorageType {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IWorkDb {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesStorageService {
    <<interface>>
    <<external>>
    📁 external_library
  }

  ErmesCachingRepository_D_ --> IdType : uses
  ErmesCachingService_DataJson_ --> DataJson : uses
  ErmesCachingService_DataJson_ --> IErmesCachingRepository : uses
  ErmesCachingService_DataJson_ --> IdType : uses
  ErmesStorageAndCaching <|-- ErmesStorageAndCachingMessages_DataJson_ : extends
  ErmesStorageAndCachingMessagesHandler --> ErmesStorageAndCachingMessages : uses
  ErmesStorageAndCachingMessagesHandler --> ErmesStorageAndCachingMessagesHandler : uses
  ErmesStorageAndCachingMessagesHandler --> IdConnectionType : uses
  ErmesStorageAndCachingMessagesHandler --> StorageType : uses
  ErmesStorageAndCaching_DataJson_ --> DataJson : uses
  ErmesStorageAndCaching_DataJson_ --> IErmesCachingService : uses
  ErmesStorageAndCaching_DataJson_ --> IErmesStorageRepository : uses
  ErmesStorageAndCaching_DataJson_ --> IdType : uses
  ErmesStorageAndCaching_DataJson_ --> _ErmesCachingServiceOptions : uses
  ErmesStorageRepository_DataJson_ --> DataJson : uses
  ErmesStorageRepository_DataJson_ --> IWorkDb : uses
  ErmesStorageRepository_DataJson_ --> IdType : uses
  ErmesStorageService_DataJson_ --> DataJson : uses
  ErmesStorageService_DataJson_ --> IErmesStorageRepository : uses
  ErmesStorageService_DataJson_ --> IdType : uses
  IErmesCachingRepository <|-- ErmesCachingRepository_D_ : extends
  IErmesCachingService <|-- ErmesCachingService_DataJson_ : extends
  IErmesStorageAndCaching <|-- ErmesStorageAndCaching_DataJson_ : extends
  IErmesStorageAndCachingMessages <|.. ErmesStorageAndCachingMessages_DataJson_ : implements
  IErmesStorageRepository <|-- ErmesStorageRepository_DataJson_ : extends
  IErmesStorageRepository <|.. MockStorageRepository_T_ : implements
  IErmesStorageRepository <|.. MockStorage_T_ : implements
  IErmesStorageService <|-- ErmesStorageService_DataJson_ : extends
  StorageType <|.. TestCacheMessage : implements
  StorageType <|.. TestCachingServiceMessage : implements
  _ErmesCachingServiceOptions --> CachingMode : uses
  _ErmesCachingServiceOptions --> _ErmesCachingServiceOptions : uses
