name: ermes_core_init
description: Composition root - DI entry points for the entire Ermes stack.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  barrel_files_annotation: ^0.3.0
  singleton_manager: ^0.6.1
  iermes:
    path: ../iermes
  ermes_core:
    path: ../ermes_core
  ermes_signaling:
    path: ../ermes_signaling
  ermes_cipher:
    path: ../ermes_cipher
  ermes_id_handler:
    path: ../ermes_id_handler
  ermes_message_control:
    path: ../ermes_message_control
  ermes_storage:
    path: ../ermes_storage
  stun_shsp: ^0.2.1
  cryptdart: ^0.2.0

  work_db: any
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.7.1
  index_generator: ^4.1.0

scripts:
  barrels:
    run: dart run build_runner build --delete-conflicting-outputs
  analyze:
    run: dart analyze
