
name: ermes_test
description: Centralized test suites for Ermes interfaces. Allows packages to verify their implementations comply with interface contracts.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  test: ^1.24.0
  work_db: ^1.2.0
  barrel_files_annotation: ^0.3.0
  iermes:
    path: ../iermes
  ermes_core:
    path: ../ermes_core
  ermes_storage:
    path: ../ermes_storage
  ermes_signaling:
    path: ../ermes_signaling
  ermes_cipher:
    path: ../ermes_cipher
  ermes_id_handler:
    path: ../ermes_id_handler
  ermes_message_control:
    path: ../ermes_message_control
  ermes_core_init:
    path: ../ermes_core_init

  nostr_signaling: ^0.6.0
  singleton_manager: ^2.2.2
  stun_shsp: ^0.4.0
  cryptdart: ^0.2.0
  crypto: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.7.1
  index_generator: ^4.1.0

  logging: any
scripts:
  barrels:
    run: dart run build_runner build --delete-conflicting-outputs

  analyze:
    run: dart analyze

