name: ermes_test
description: Centralized test suites for Ermes interfaces. Allows packages to verify their implementations comply with interface contracts.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  test: ^1.24.0
  iermes: 
    path: ../iermes
  ermes_types:
    path: ../types
  barrel_files_annotation: ^0.2.0

dev_dependencies:
  lints: ^3.0.0
  barrel_files: ^0.2.0
  build_runner: ^2.0.0
