
name: ermes_test
description: Centralized test suites for Ermes interfaces. Allows packages to verify their implementations comply with interface contracts.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  test: ^1.24.0
  work_db: ^1.1.0
  iermes:
    path: ../iermes
  ermes_core:
    path: ../ermes_core
  ermes_storage:
    path: ../ermes_storage
  ermes_signaling:
    path: ../ermes_signaling

  barrel_files_annotation: ^0.2.0
  shsp_implementations: ^1.0.6

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.0.0

