classDiagram
  class _TestErmesRepository {
    <<class>>
    📁 ermes_encryption_decryption_test.dart
  }
  class _Random {
    <<class>>
    📁 ermes_encryption_decryption_test.dart
  }
  class _SimpleRepository {
    <<class>>
    📁 ermes_newkey_callback_unit_test.dart
  }
  class _FakeErmesService {
    <<class>>
    📁 ermes_peer_test.dart
  }
  class _TestStorage {
    <<class>>
    📁 ermes_service_retransmission_test.dart
  }
  class _TestMessageControlService {
    <<class>>
    📁 ermes_service_retransmission_test.dart
  }
  class PeerTestHelper {
    <<class>>
    📁 peer_test_helper.dart
  }
  class InterfaceTestConfig {
    <<class>>
    📁 integration.dart
  }
  class InterfaceFactories {
    <<class>>
    📁 integration.dart
  }
  class MultiPeerFactories {
    <<class>>
    📁 integration.dart
  }
  class _DummyConnection {
    <<class>>
    📁 connections_and_handshake_test_suite.dart
  }
  class _TestSignalErmes {
    <<class>>
    📁 signaling_server_test_suite.dart
  }
  class PeerInstance {
    <<class>>
    📁 multi_peer_framework.dart
  }
  class MultiPeerTestFramework {
    <<class>>
    📁 multi_peer_framework.dart
  }
  class IErmesRepository {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class Uint8List {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IdAccountType {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class ServiceMessageNewKey {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesService {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class TypeOfDataExternal {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class CallbackOnDataArrived {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class CallbackOnDataSending {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class CallbackOnDataSent {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class CallbackOnNewKey {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesStorageAndCaching {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IdType {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class MessageType {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesMessageControlService {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class CallbackIdsToRequest {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IIdHandlerService {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IErmesConnection {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class IdPeer {
    <<interface>>
    <<external>>
    📁 external_library
  }
  class ISignalErmes {
    <<interface>>
    <<external>>
    📁 external_library
  }

  IErmesConnection <|.. _DummyConnection : implements
  IErmesMessageControlService <|.. _TestMessageControlService : implements
  IErmesRepository <|.. _SimpleRepository : implements
  IErmesRepository <|.. _TestErmesRepository : implements
  IErmesService <|.. _FakeErmesService : implements
  IErmesStorageAndCaching <|.. _TestStorage : implements
  ISignalErmes <|.. _TestSignalErmes : implements
  MultiPeerTestFramework --> PeerInstance : uses
  MultiPeerTestFramework --> Uint8List : uses
  PeerInstance --> IErmesConnection : uses
  PeerInstance --> IErmesRepository : uses
  PeerInstance --> IErmesService : uses
  PeerInstance --> IIdHandlerService : uses
  PeerTestHelper --> IIdHandlerService : uses
  PeerTestHelper --> Uint8List : uses
  _DummyConnection --> IErmesRepository : uses
  _DummyConnection --> IdPeer : uses
  _FakeErmesService --> CallbackOnDataArrived : uses
  _FakeErmesService --> CallbackOnDataSending : uses
  _FakeErmesService --> CallbackOnDataSent : uses
  _FakeErmesService --> CallbackOnNewKey : uses
  _FakeErmesService --> IErmesRepository : uses
  _FakeErmesService --> TypeOfDataExternal : uses
  _SimpleRepository --> IdAccountType : uses
  _SimpleRepository --> Uint8List : uses
  _TestErmesRepository --> Uint8List : uses
  _TestMessageControlService --> CallbackIdsToRequest : uses
  _TestMessageControlService --> IdType : uses
  _TestStorage --> IdType : uses
  _TestStorage --> MessageType : uses
