name: ermes_cipher
description: Cryptographic implementation for Ermes with multi-key rotation support
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  meta: ^1.11.0
  cryptdart: ^0.2.0
  crypto: ^3.0.0
  barrel_files_annotation: ^0.3.0
  singleton_manager: ^0.6.1
  iermes:
    path: ../iermes

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.7.1
  index_generator: ^4.1.0
  singleton_manager_generator: ^1.4.0

scripts:
  barrels:
    run: dart run build_runner build --delete-conflicting-outputs

  analyze:
    run: dart analyze
