name: iermes
description: Interfaces and abstract classes for the Ermes messaging system
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.4 <5.0.0"

dependencies:
  meta: ^1.11.0
  ermes_types:
    path: ../types
  barrel_files_annotation: ^0.2.0
  shsp_interfaces: ^1.0.0
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.0.0
  barrel_files: ^0.2.0