import 'package:iermes/iermes.dart';
import 'package:nostr_signaling/nostr_signaling.dart';
import 'package:stun_shsp/stun_shsp.dart';
import 'package:stun_shsp/stun_shsp.dart' as stun_shsp;

import 'book/ermes_book_repository.dart';
import 'book/ermes_book_service.dart';
import 'handler/ermes_signaling_handler.dart';
import 'handler/ermes_signaling_repository.dart';
import 'main_injection.dart';

/// Ready-to-use injector for the ermes_signaling stack.
///
/// Hand-maintained on purpose, in its own file: `main_injection.dart` is
/// regenerated by `singleton_manager_generator` (`melos run
/// singleton_generator:ermes_signaling`), which overwrites that file whole —
/// anything added there would be lost on the next run.
///
/// On top of the classes carrying a generated `dependencyInjectionFactory`, it
/// supplies the inputs that graph resolves but does not own: the Nostr
/// [INostrSignaling] client (built from [keyPair]/[relayUrls]/
/// [useCompression] via `NostrSignalingInjection`), this peer's
/// [IdAccountType], and — when [initializeStunShsp] is true — the STUN/SHSP
/// stack that [ErmesSignalingHandler] resolves under the `ipv4` subkey.
///
/// Use [registerAllSingletonsErmesSignalingAsync] — the sync variant cannot
/// generate a key pair, register the Nostr client, or open the relay
/// connection.
class ErmesSignalingInjector with MainInjectionErmesSignalingMixin {
  /// Creates an injector, optionally reusing an existing [keyPair] and
  /// [accountId], and controlling whether the STUN/SHSP stack and the relay
  /// WebSockets are set up eagerly.
  const ErmesSignalingInjector({
    this.keyPair,
    this.relayUrls,
    this.accountId,
    this.useCompression = false,
    this.initializeStunShsp = false,
    this.connectSignaling = false,
  });

  /// Nostr key pair identifying this peer on the signaling network. A fresh
  /// pair is generated when null.
  final NostrKeyPair? keyPair;

  /// Relay WebSocket URLs to publish and subscribe signals through.
  final List<String>? relayUrls;

  /// This peer's account identifier. Defaults to the key pair's public key
  /// when null.
  final IdAccountType? accountId;

  /// Whether signal payloads are gzip-compressed.
  final bool useCompression;

  /// Whether to bind the SHSP sockets and STUN handlers under the `ipv4`
  /// subkey via the stun_shsp package's own injector.
  final bool initializeStunShsp;

  /// Whether to open the relay WebSockets straight away.
  final bool connectSignaling;

  /// Bridges the generic interface entries the generator registered under
  /// their raw (unparameterized) type to the concrete singleton, so callers
  /// resolving [IErmesSignalingHandler]`<ShspPeer>` (from `ermes_core`) or
  /// `<IShspPeer>` (from [ErmesSignalingRepository]) and
  /// [IErmesSignalingRepository]`<ISignalErmes>` (from `ErmesSignalingService`)
  /// all share the one instance the raw entry lazily creates.
  @override
  void afterRegisterAllSingletonsErmesSignaling({String key = 'default'}) {
    RegistryManager.instance
      ..connectInstance<IErmesBookRepository<BookData>, ErmesBookRepository>(
        () =>
            RegistryManager.instance.getInstance<IErmesBookRepository<dynamic>>(
                  key: key,
                )
                as ErmesBookRepository,
        key: key,
      )
      ..connectInstance<IErmesBookService<BookData>, ErmesBookServiceBase>(
        () =>
            RegistryManager.instance.getInstance<IErmesBookService<dynamic>>(
                  key: key,
                )
                as ErmesBookServiceBase,
        key: key,
      )
      ..connectInstance<
        IErmesSignalingHandler<IShspPeer>,
        ErmesSignalingHandler
      >(
        () =>
            RegistryManager.instance
                    .getInstance<IErmesSignalingHandler<dynamic>>(key: key)
                as ErmesSignalingHandler,
        key: key,
      )
      ..connectInstance<
        IErmesSignalingHandler<ShspPeer>,
        ErmesSignalingHandler
      >(
        () =>
            RegistryManager.instance
                    .getInstance<IErmesSignalingHandler<dynamic>>(key: key)
                as ErmesSignalingHandler,
        key: key,
      )
      ..connectInstance<
        IErmesSignalingRepository<ISignalErmes>,
        ErmesSignalingRepository
      >(
        () =>
            RegistryManager.instance
                    .getInstance<IErmesSignalingRepository<dynamic>>(key: key)
                as ErmesSignalingRepository,
        key: key,
      );
  }

  @override
  Future<void> beforeRegisterAllSingletonsErmesSignalingAsync({
    String key = 'default',
  }) async {
    if (initializeStunShsp) {
      await stun_shsp.initializeStunShsp(key: key);
    }

    final resolvedKeyPair = keyPair ?? NostrKeys.generate();
    await NostrSignalingInjection(
      keyPair: resolvedKeyPair,
      relayUrls: relayUrls,
      useCompression: useCompression,
    ).registerAllSingletonsNostrSignalingAsync(key: key);

    RegistryManager.instance.setInstance<IdAccountType>(
      accountId ?? resolvedKeyPair.publicKey,
      key: key,
    );

    if (connectSignaling) {
      await RegistryManager.instance
          .getInstance<INostrSignaling>(key: key)
          .connect();
    }
  }
}
